### ISSUE TITLE
Issue with the update script for branch names

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Shell-Scripts#17]
Should the `update` script more clearly state that to work the branch names need to be fully qualified ie. `origin/staging` as opposed to simply `staging`?

**Comment by beporter** [comment]
Is anyone going to object if I close this as `wontfix`? I don't think there's much reason to mess with the Cake 2 branch much anymore-- it's operational as-is, even with the (well known) gotchas.

**Comment by ricog** [comment]
We'll be ok.

**Comment by jtyost2** [comment]
Yeah, same here.
