### ISSUE TITLE
Create a Shell Script to Remove/Clean Composer Managed Directories then run install

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Shell-Scripts#31]
So run `rm -rf ./Vendor/* && rm -rf ./bin/* && composer install --dev` basically?

This is a pretty common action especially when switching between branches.

**Comment by beporter** [comment]
As an additional safety precaution, if the script can not detect the presence of version control (`.git/` directory or svn's equivelent maybe?) that could be used as a safety net for an erroneous delete, maybe it should refuse to perform the delete without a prompt of a `-y` flag to force it.

**Comment by beporter** [comment]
The best place to extend this work is probably from #35.
