### ISSUE TITLE
Installation failed, reverting ./composer.json to its original content.

### ISSUE THREAD

**Issue by Oxicode** [loadsys/CakePHP-Shell-Scripts#82]
![image](https://cloud.githubusercontent.com/assets/1320709/23190140/3a38ca46-f864-11e6-8a22-e58aa76d8821.png)

**Comment by justinyost** [comment]
Hi @Oxicode can you provide more details into which version you tried to install and what failed specifically. Thanks.

**Comment by Oxicode** [comment]
@justinyost here composer.json in pastebin

http://pastebin.com/1e7Fb8eJ

**Comment by justinyost** [comment]
@Oxicode sorry for the delay in responding. I was able to have this successfully install with PHP version 7.0. Can you provide the PHP version this failed on?

**Comment by Oxicode** [comment]
my version of PHP is 5.6

**Comment by justinyost** [comment]
I've looked into this and verified that we can generate a correct and valid installation on PHP 5.6. In fact I created a branch to add Travis builds to https://github.com/loadsys/CakePHP-Shell-Scripts/pull/83 verify installations occur correctly for PHP 5.6 -> 7.1
